before_build:
    - cmd: nuget restore

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '1.0.0.0'
  file_version: '1.0.0.0' 
  informational_version: '1.0.0.0'

build:
  verbosity: minimal

test: off

artifacts:
- path: '**\*.nupkg'
  name: nupkg


deploy:
- provider: NuGet
  server: https://www.myget.org/F/obsidian/api/v2/package
  api_key:
    secure: Q9v7Huzgx+vJC3E8oGhw/mART6brch/Dg+OIJLCo2YCdexCBCMb0/8Nay/Ldq07o
  skip_symbols: false
  symbol_server: https://www.myget.org/F/obsidian/api/v3/index.json
  artifact: /.*(\.|\.s)nupkg/
  on:
    branch: master